### ISSUE TITLE
Can you help me with this dataset please?

### ISSUE THREAD

**Issue by rana-98** [UmbertoAzadi/OUTLINE#3]
@uazadi 
i am using your data-set in my graduation project" code smell detection using deep learning " and i have a problem of preprocessing this dataset and  also im trying to write a textual feature extraction script to convert the tokens to vector that then feed to network.
i can't fully understand the dataset and i would like if you may help me.

**Comment by uazadi** [comment]
Hello there!
First of all, thank you for the interest :)

About the datasets:
- The meaning of the attributes are the following:
  - **IDType** is simply an ID
  - **project** is the root folder of source code in the project
  - **package** is the package as specified in the java class  
  - **complextype** is the name of the class 
    - sometimes the full name with the package is specified (that is actually a bug)
    - if the Class is nested in another then you find NameFirstClass.NameNestedClass
  - **method** the name of the method with the list of parameters types
  - then there is the list of all the software quality metrics with which the ML algorithms are actually trained, if you are not familiar with some of them you can find the definitions in this file: [metric-definitions.pdf](https://drive.google.com/file/d/1Mg1GuLGeKr_53peY1Lqqkq_xs85VtiO2/view?usp=sharing)
  - finally there is the label (affected or not by the code smell)

Now some of the first attributes might sound weird but remember that the creation of these datasets is fully automated.

Anyway for what concerns the problems in the preprocessing, I am not surprised that you might find some problems. These datasets are created explicitly to be loaded in WEKA, nothing else.

Now the values with which you will most likely have problems are the textual one:
  - **project**,  **package** and **complextype** are never between quotes, but some character might be considered as special by some library (especially if you are using python)
  - **method** is between _single_ quotes only if the method has more then one parameter (that is because in that case the parameters' type are separated by comma)

To fix these problems most likely you just need to wrap all these values around the characters tah the library that you are using exploit to identify strings (my best guess would be double quotes but you need to look it up). Then, very often the deep learning library such as Keras or TF have build-in preprocessing algorithms to create numeric vectors out of single strings attributes.

But still, it might be worth asking yourself if you really need all these string fields for the classification. Especially I would suggest to filter out at least the attributes IDType and project.

I hope this reply is exhaustive enough, if not please do not hesitate to comment back :)

Best,
Umberto

**Comment by rana-98** [comment]
Thank you for your generous reply,
I'm sorry but i still have questions. i'm considering deleting the 2 columns of Id type and project path. 

1. But will it cause a problem ?
2. I m considering making my data-set multi-label so i would join the class level smells as God Class and data Class is that possible by code or should i do it manually in Excel ? and do you know or recommend a link about multi-label classification using this data-set?
3. and i don't know which is the method attribute i only have till the complexity and then the metrics 

4. Finally,  i want to understand this part more if you may (_wrap all these values around the characters tah the library that you are using exploit to identify strings_)  i m using python and TF-IDF to create numeric vectors and LSTM architecture in the deep learning.

Thank you so much for your reply and consideration. 
Rana

**Comment by rana-98** [comment]
@uazadi

**Comment by uazadi** [comment]
Hello again,
1. I don't see how filter out a column might create a problem from, let's say, a technical point of view, it's not like there is a DSL to comply with. Semantically speaking is another story, it's up to you to understand if it might be helpful to keep in consideration the project. To give you a better idea regarding this specific domain, you might want to keep into consideration the project because, for example, you work under the assumption that different projects are developed by different teams, each with a different definition of the code smell (remember [smells don't always indicate a problem](https://martinfowler.com/bliki/CodeSmell.html)). Or you can state that you want to get a more general detector and you can even decide to remove all the text fields because, at the end of the day, each instance represents a method/class and the name of that class/method is not actually informative. Both are valid approaches but you need to select one, plus this is just theory, you might want to use both approaches and see if the text attributes are actually useful to the ML algorithm or not.

2. If for code you mean OUTLINE the answer is no, if you mean in general if there is a library that handles the process for you, I am not aware of any but you can try to have a look. I wouldn't be surprised to find something in python that eases this process, and in any case, create a custom script in python that takes care of this merging step is not that hard. 
However, if you had a look at the way in which these datasets have been created you should have understood that the instances in each dataset are not the same because the classes/methods in each dataset are just a sample of all the classes/methods in the project. And the sampling is designed differently for each code smell. **So I wouldn't say that these datasets are the most appropriate one for a multi-label classification.**
On top of that, I encouraged you to be careful with the multi-label classification, you are adding a lot of complexity so make sure it's justified. Mix the Data Class and God class datasets might not be that useful, a God Class is also a Data Class sounds a lot as a contradiction in terms. However, I wouldn't say the same thing about a Long Method that is also a Feature Envy, I find that way more likely to appear.

3. You will see the method attribute only in the dataset related to code smells at method level, such as Feature Envy and Long Method. (go in the [codesmell](https://github.com/uazadi/OUTLINE/tree/master/codesmells) folder of the repo, there the datasets are well organized)

4. What I mean is that all libraries accept the CSV format, but unfortunately each requires a different set of symbols, like for separation you might need to use a comma, semicolon, tab, space, etc. 
Now there should be one symbol that allows you to wrap a string in which for example the character that you use for the separation is contained but you don't want the library to consider it as a separator. For example in WEKA such character is the single-quote and the separator is the comma, so if I want to add the string: _calculateSum(int, int)_ I can't just add that string otherwise the comma in the string will be considered as a separator, therefore, the workaround in WEKA is to wrap that string in single quotes like this: _'calculateSum(int, int)'_. You need to find the equivalent character for your library.

**Comment by uazadi** [comment]
Hey @rana-98,
I am assuming that I answered your questions, if not don't hesitate to reopen this issue of open a new one.

Best,
Umberto

**Comment by rana-98** [comment]
Yes thank you so much for your help and response <3
